from utils import *

# Consume energy to gain skills
TRAINING_RECIPES = [
    Recipe({RESOURCE_ENERGY: 5}, skill_improvements={SKILL_CHOPPING: 1}),
    Recipe({RESOURCE_ENERGY: 5}, skill_improvements={SKILL_MINING: 1}),
    Recipe({RESOURCE_ENERGY: 5}, skill_improvements={SKILL_FISHING: 1}),
    Recipe({RESOURCE_ENERGY: 5}, skill_improvements={SKILL_CRAFTING: 0.5})
]

# Consume food items to gain energy
EATING_RECIPES = [
    Recipe({RESOURCE_FRUIT: 1}, {RESOURCE_ENERGY: 3}),
    Recipe({RESOURCE_RAW_FISH: 1}, {RESOURCE_ENERGY: 2.5}),
    Recipe({RESOURCE_COOKED_FISH: 1}, {RESOURCE_ENERGY: 10}),
]

# Consume items to obtain other items
CRAFTING_RECIPES = [
    Recipe({RESOURCE_ENERGY: 1, RESOURCE_WOOD: 1, RESOURCE_RAW_FISH: 1}, {RESOURCE_COOKED_FISH: 1}, {SKILL_CRAFTING: 1}, {RESOURCE_WOOD: 0.1}, {SKILL_CRAFTING: 0.2}, {RESOURCE_WOOD: 0.5}),
    Recipe({RESOURCE_ENERGY: 4, RESOURCE_WOOD: 2, RESOURCE_ORE: 1}, {RESOURCE_AXE: 1}, {SKILL_CRAFTING: 1}, {RESOURCE_WOOD: 0.15}, {SKILL_CRAFTING: 0.4}, {RESOURCE_WOOD: 1}),
    Recipe({RESOURCE_ENERGY: 6, RESOURCE_WOOD: 1, RESOURCE_ORE: 2}, {RESOURCE_PICKAXE: 1}, {SKILL_CRAFTING: 1}, {RESOURCE_ORE: 0.15}, {SKILL_CRAFTING: 0.5}, {RESOURCE_ORE: 1}),
    Recipe({RESOURCE_ENERGY: 5, RESOURCE_WOOD: 3, RESOURCE_FRUIT: 1}, {RESOURCE_FISHING_ROD: 1}, {SKILL_CRAFTING: 1}, {RESOURCE_WOOD: 0.1}, {SKILL_CRAFTING: 0.3}, {RESOURCE_WOOD: 1.5}),
    Recipe({RESOURCE_ENERGY: 10, RESOURCE_WOOD: 5, RESOURCE_ORE: 5}, {RESOURCE_SWORD: 1}, {SKILL_CRAFTING: 1}, {RESOURCE_ORE: 0.25}, {SKILL_CRAFTING: 0.75}, {RESOURCE_ORE: 2.5})
]

ORDERED_RECIPES = TRAINING_RECIPES + EATING_RECIPES + CRAFTING_RECIPES
RECIPESET = set(ORDERED_RECIPES)